[workspace]
members = [
    "aether-core",
    "examples/anti-afk",
    "examples/stone-miner",
    "plugins/anti-afk",
    "plugins/auto-mine",
    "plugins/discord",
    "plugins/task-manager",
    "plugins/utility"
]

resolver = "2"
