[workspace]
members = [
    "aether-core",
    "examples/anti-afk",
    "examples/stone-miner",
    "multi-azalea",
    "plugins/anti-afk",
    "plugins/task-manager",
    "plugins/utility"
]

resolver = "2"
