[package]
name = "aether-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
azalea = { git = "https://github.com/azalea-rs/azalea", branch = "1.20.4" }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["macros"] }
serde = { version = "1.0.201", features = ["derive"] }
parking_lot = "0.12.2"
