[package]
name = "aether-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", branch = "1.20.4", version = "0.9.1" }
tokio = { version = "1.37.0", features = ["macros"] }
