name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.79.0
  RUST_VERSION_NIGHTLY: nightly-2024-06-22
  CRATE_PATHS: .

jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_NIGHTLY }}
          profile: minimal
          override: true
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy
