name: PR

on:
  pull_request:
    branches:
      - main
      - release/*

env:
  CARGO_TERM_COLOR: always
  CRATE_PATHS: .

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
      - name: Identify rust toolchain
        id: toolchain
        uses: jaywcjlove/github-action-read-file@main
        with:
          localfile: rust-toolchain
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.content }}
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo test
        run: cargo test

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Identify rust toolchain
        id: toolchain
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: rust-toolchain
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.toolchain.outputs.content }}
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
